/** Fallback: one emoji per grocery category. */
export const CATEGORY_EMOJI: Record<string, string> = {
  Vegetables: '🥦',
  Dairy: '🥛',
  Fruits: '🍎',
  Snacks: '🍿',
  Grains: '🌾',
  Pulses: '🫘',
  Spices: '🌶️',
  Bakery: '🍞',
  Beverages: '🧃',
  'Oils & Sauces': '🫙',
  Cleaning: '🧹',
  Other: '🛒',
};

/**
 * Per-item keyword -> emoji map.
 * Keys are lowercase substrings matched against item names via .includes().
 * Sorted longest-first at module load to avoid partial shadowing
 * (for example, "apple juice" matches before "apple").
 */
const ITEM_EMOJI_MAP: Record<string, string> = {
  // Vegetables
  'bitter gourd': '🥒',
  'curry leaves': '🌿',
  'bell pepper': '🫑',
  'spring onion': '🌿',
  'green chilli': '🌶️',
  'green chili': '🌶️',
  'red chilli': '🌶️',
  'red chili': '🌶️',
  'lady finger': '🌿',
  drumstick: '🌿',
  tamatar: '🍅',
  takkali: '🍅',
  thakkali: '🍅',
  tomato: '🍅',
  onion: '🧅',
  pyaz: '🧅',
  piaz: '🧅',
  ullipaya: '🧅',
  ullipayalu: '🧅',
  eerulli: '🧅',
  vengayam: '🧅',
  potato: '🥔',
  aloo: '🥔',
  aalu: '🥔',
  alu: '🥔',
  urulaikizhangu: '🥔',
  garlic: '🧄',
  velluli: '🧄',
  poondu: '🧄',
  bellulli: '🧄',
  carrot: '🥕',
  cucumber: '🥒',
  capsicum: '🫑',
  broccoli: '🥦',
  mushroom: '🍄',
  eggplant: '🍆',
  brinjal: '🍆',
  baingan: '🍆',
  vankaya: '🍆',
  badnekai: '🍆',
  kathirikkai: '🍆',
  spinach: '🥬',
  cabbage: '🥬',
  lettuce: '🥬',
  palak: '🥬',
  methi: '🌿',
  coriander: '🌿',
  cilantro: '🌿',
  kothimera: '🌿',
  kothamalli: '🌿',
  kottambari: '🌿',
  karivepaku: '🌿',
  kariveppilai: '🌿',
  karibevu: '🌿',
  pumpkin: '🎃',
  corn: '🌽',
  peas: '🫛',
  avocado: '🥑',
  ginger: '🌿',
  chilli: '🌶️',
  chili: '🌶️',
  mirapakaya: '🌶️',
  mirapakayalu: '🌶️',
  menasinakai: '🌶️',
  milagai: '🌶️',
  okra: '🌿',
  bhindi: '🌿',
  bendakaya: '🌿',
  bendekai: '🌿',
  vendaikkai: '🌿',

  // Fruits
  watermelon: '🍉',
  pineapple: '🍍',
  strawberry: '🍓',
  blueberry: '🫐',
  raspberry: '🍓',
  coconut: '🥥',
  banana: '🍌',
  kela: '🍌',
  arati: '🍌',
  vazhapazham: '🍌',
  'bale hannu': '🍌',
  mango: '🥭',
  aam: '🥭',
  mamidi: '🥭',
  'maavina hannu': '🥭',
  orange: '🍊',
  grapes: '🍇',
  draksha: '🍇',
  drakshi: '🍇',
  lemon: '🍋',
  lime: '🍋',
  nimbu: '🍋',
  nimmakaya: '🍋',
  elumichai: '🍋',
  'nimbe hannu': '🍋',
  peach: '🍑',
  cherry: '🍒',
  apple: '🍎',
  kiwi: '🥝',
  pear: '🍐',
  papaya: '🍈',
  papita: '🍈',
  boppayi: '🍈',
  pappali: '🍈',
  guava: '🍈',
  litchi: '🍈',
  pomegranate: '🍎',
  anar: '🍎',
  danimma: '🍎',
  daalimbe: '🍎',
  tamarind: '🍋',
  imli: '🍋',
  chintapandu: '🍋',

  // Dairy and protein
  paneer: '🧀',
  cheese: '🧀',
  butter: '🧈',
  ghee: '🧈',
  tuppa: '🧈',
  neyyi: '🧈',
  nei: '🧈',
  yogurt: '🫙',
  curd: '🫙',
  dahi: '🫙',
  perugu: '🫙',
  thayir: '🫙',
  mosaru: '🫙',
  cream: '🫙',
  lassi: '🥛',
  milk: '🥛',
  doodh: '🥛',
  dudh: '🥛',
  paalu: '🥛',
  palu: '🥛',
  paal: '🥛',
  haalu: '🥛',
  halu: '🥛',
  egg: '🥚',
  anda: '🥚',
  ande: '🥚',
  muttai: '🥚',
  guddu: '🥚',
  guddlu: '🥚',
  motte: '🥚',

  // Grains
  noodles: '🍜',
  pasta: '🍝',
  poha: '🌾',
  oats: '🥣',
  rice: '🍚',
  chawal: '🍚',
  biyyam: '🍚',
  arisi: '🍚',
  akki: '🍚',
  bread: '🍞',
  roti: '🫓',
  atta: '🌾',
  aata: '🌾',
  flour: '🌾',
  maida: '🌾',
  rava: '🌾',
  ravai: '🌾',
  sooji: '🌾',
  suji: '🌾',
  semolina: '🌾',
  pindi: '🌾',
  hittu: '🌾',
  wheat: '🌾',

  // Pulses
  chickpea: '🫘',
  lentil: '🫘',
  rajma: '🫘',
  chhole: '🫘',
  moong: '🫘',
  masoor: '🫘',
  urad: '🫘',
  toor: '🫘',
  chana: '🫘',
  dal: '🫘',
  pappu: '🫘',
  bele: '🫘',

  // Spices and condiments
  turmeric: '🌿',
  haldi: '🌿',
  pasupu: '🌿',
  manjal: '🌿',
  arishina: '🌿',
  cumin: '🌿',
  jeera: '🌿',
  jeelakarra: '🌿',
  seeragam: '🌿',
  jeerige: '🌿',
  mustard: '🌿',
  sarson: '🌿',
  kadugu: '🌿',
  sasive: '🌿',
  pepper: '🌶️',
  cinnamon: '🌿',
  cardamom: '🌿',
  saffron: '🌿',
  jaggery: '🍯',
  bellam: '🍯',
  bella: '🍯',
  honey: '🍯',
  sugar: '🧂',
  cheeni: '🧂',
  chini: '🧂',
  chakkera: '🧂',
  sakkarai: '🧂',
  sakkare: '🧂',
  salt: '🧂',
  namak: '🧂',
  uppu: '🧂',

  // Snacks
  popcorn: '🍿',
  chocolate: '🍫',
  biscuit: '🍪',
  cookie: '🍪',
  cashew: '🥜',
  kaju: '🥜',
  jeedipappu: '🥜',
  munthiri: '🥜',
  almond: '🥜',
  badam: '🥜',
  peanut: '🥜',
  mungfali: '🥜',
  pallilu: '🥜',
  kadalekai: '🥜',
  nuts: '🥜',
  chips: '🥔',

  // Bakery
  cake: '🎂',
  muffin: '🧁',
  croissant: '🥐',
  bun: '🍔',
  pav: '🍞',

  // Beverages
  coffee: '☕',
  chai: '🍵',
  tea: '🍵',
  juice: '🧃',
  water: '💧',
  cola: '🥤',
  soda: '🥤',

  // Oils and sauces
  ketchup: '🍅',
  pickle: '🫙',
  sauce: '🫙',
  vinegar: '🫙',
  oil: '🫙',
  tel: '🫙',
  nune: '🫙',
  ennai: '🫙',
  enne: '🫙',
  yenne: '🫙',
  jam: '🍯',

  // Meat and protein
  chicken: '🍗',
  prawn: '🍤',
  shrimp: '🍤',
  fish: '🐟',
  mutton: '🥩',
  meat: '🥩',

  // Cleaning
  shampoo: '🧴',
  conditioner: '🧴',
  detergent: '🧺',
  dishwash: '🧼',
  soap: '🧼',
  sanitizer: '🧼',
  dettol: '🧼',
  broom: '🧹',
};

// Pre-sort longest-first so multi-word keys match before single-word substrings.
const SORTED_KEYS = Object.keys(ITEM_EMOJI_MAP).sort((a, b) => b.length - a.length);

/**
 * Returns the most specific emoji for an item.
 * Tries item-name keyword match first; falls back to category emoji.
 */
export function getItemEmoji(name: string, category: string): string {
  const lower = name.toLowerCase();
  for (const keyword of SORTED_KEYS) {
    if (lower.includes(keyword)) {
      return ITEM_EMOJI_MAP[keyword];
    }
  }

  return CATEGORY_EMOJI[category] ?? '🛒';
}
